### ISSUE TITLE
Travis badge && webhook

### ISSUE THREAD

**Issue by mburns** [goru97/ele-cassandra#6]
Since Travis is working, we should wire it up. https://travis-ci.org/goru97/ele-cassandra

Badge to add to `readme.md`:

```
[![Build Status](https://travis-ci.org/goru97/ele-cassandra.svg?branch=master)](https://travis-ci.org/goru97/ele-cassandra)
```

Ensure that there is a webhook/service integration with Travis, so that it builds on each commit/PR

**Comment by goru97** [comment]
Done and also double checked the webhook.
