### ISSUE TITLE
Dependencies in metadata.rb should be reflected in berksfile

### ISSUE THREAD

**Issue by mburns** [goru97/ele-cassandra#7]
There are various opinions on how to handle this, but MMI cookbooks tend to have any dependencies listed in `metadata.rb` (apt, python, java, etc) also be listed in `Berksfile`.

Version locking to a specific cookbook should generally happen in the Berksfile, but not the metadata file.

**Comment by goru97** [comment]
@mburns Can you please take a look at this one.

**Comment by mburns** [comment]
You fixed this in https://github.com/goru97/ele-cassandra/commit/2d62dd71603236ba29a2142f80bb36c71abd6c53

**Comment by goru97** [comment]
Great!
